/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103c6_USART_Driver.h"
#include "custom_bootloader.h"

void wait(uint8_t delay)
{
	uint8_t i, j;
	for(i = 0; i < delay; i++)
		for(j = 0; j < 255; j++);
}

int main(void)
{
	BL_Init();

    /* Loop forever */
	while(1)
	{
		debug_message((uint8_t*)"Hello From Debug UART\r\n");
		MCAL_USART_sendString(HOST_UART, (uint8_t*)"Welcome From Host UART\r\n");
		wait(100);

	}
}
